- name: update package list
  become: true
  package:
    update_cache: yes

- name: upgrade all packages
  become: true
  package:
    name: "*"
    state: latest

- name: Install packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    # base packages
    - vim
    - git
    - curl
    - tmux
    - unzip
    # asdf dependencies
    - automake
    - autoconf
    - libreadline-dev
    - libncurses-dev
    - libssl-dev
    - libyaml-dev
    - libxslt-dev
    - libffi-dev
    - libtool
    - unixodbc-dev
    - build-essential
    - m4
    - libncurses5-dev
    - libwxgtk3.0-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libpng-dev
    - unixodbc-dev
    - xsltproc
    - fop
