- name: download terraform package
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /var/tmp/terraform-{{ terraform_version }}.zip
    checksum: "sha256:{{ terraform_shasum }}"

- name: unzip terraform package
  unarchive:
    src: "/var/tmp/terraform-{{ terraform_version }}.zip"
    dest: "/var/tmp/"

- name: add terraform binary to path
  become: true
  copy:
    src: /var/tmp/terraform
    dest: /usr/local/bin/terraform
    mode: 0755
